In [1]:
from numpy import array
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
 
# 1. 데이터
x = array([[230, 2048, 114, 4107, 266, 87639.24219], [230,2048,114,4107,266,87639.24219], [230,2048,114,4107,266,87639.24219], [230,2048,114,4107,266,87639.24219]])
x.astype(np.float32)
y = array([60,59.9,59.8,59.6])
y.astype(np.float32)

array([60. , 59.9, 59.8, 59.6], dtype=float32)

In [2]:
print('x shape : ', x.shape) # (4,3)
print('y shape : ', y.shape) # (4,)
#  x  y
# 123 4
# 234 5
# 345 6
# 456 7

x shape :  (4, 6)
y shape :  (4,)


In [3]:
print(x)
print('-------x reshape-----------')
x = x.reshape((x.shape[0], x.shape[1], 1)) # (4,3,1) reshape 전체 곱 수 같아야 4*3=4*3*1
print('x shape : ', x.shape)
print(x)
#  x        y
# [1][2][3] 4
# .....

[[  230.       2048.        114.       4107.        266.      87639.24219]
 [  230.       2048.        114.       4107.        266.      87639.24219]
 [  230.       2048.        114.       4107.        266.      87639.24219]
 [  230.       2048.        114.       4107.        266.      87639.24219]]
-------x reshape-----------
x shape :  (4, 6, 1)
[[[  230.     ]
  [ 2048.     ]
  [  114.     ]
  [ 4107.     ]
  [  266.     ]
  [87639.24219]]

 [[  230.     ]
  [ 2048.     ]
  [  114.     ]
  [ 4107.     ]
  [  266.     ]
  [87639.24219]]

 [[  230.     ]
  [ 2048.     ]
  [  114.     ]
  [ 4107.     ]
  [  266.     ]
  [87639.24219]]

 [[  230.     ]
  [ 2048.     ]
  [  114.     ]
  [ 4107.     ]
  [  266.     ]
  [87639.24219]]]


In [24]:
# 2. 모델 구성
model = Sequential()
model.add(LSTM(10, activation = 'relu', input_shape=(6,1)))
# DENSE와 사용법 동일하나 input_shape=(열, 몇개씩잘라작업)
model.add(Dense(10))
model.add(Dense(1))
 
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_6 (LSTM)                (None, 10)                480       
_________________________________________________________________
dense_12 (Dense)             (None, 10)                110       
_________________________________________________________________
dense_13 (Dense)             (None, 1)                 11        
Total params: 601
Trainable params: 601
Non-trainable params: 0
_________________________________________________________________


In [25]:
# 3. 실행
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=100, batch_size=1)

Train on 4 samples
Epoch 1/100
4/4 [==============================] - 1s 341ms/sample - loss: 4534128.1875
Epoch 2/100
4/4 [==============================] - 0s 4ms/sample - loss: 1772023.9219
Epoch 3/100
4/4 [==============================] - 0s 5ms/sample - loss: 362237.8223
Epoch 4/100
4/4 [==============================] - 0s 5ms/sample - loss: 25559.3701
Epoch 5/100
4/4 [==============================] - 0s 4ms/sample - loss: 207481.1309
Epoch 6/100
4/4 [==============================] - 0s 5ms/sample - loss: 329634.8984
Epoch 7/100
4/4 [==============================] - 0s 4ms/sample - loss: 243207.3438
Epoch 8/100
4/4 [==============================] - 0s 5ms/sample - loss: 89398.2695
Epoch 9/100
4/4 [==============================] - 0s 4ms/sample - loss: 8263.3889
Epoch 10/100
4/4 [==============================] - 0s 5ms/sample - loss: 11954.9722
Epoch 11/100
4/4 [==============================] - 0s 5ms/sample - loss: 34978.4150
Epoch 12/100
4/4 [============================

In [26]:
x_input = array([[230,2048,114,4107,266,87639.24219]])
x_input = x_input.reshape((1,6,1))
x_input = tf.cast(x_input, tf.float32)
x_input

<tf.Tensor: id=15511, shape=(1, 6, 1), dtype=float32, numpy=
array([[[  230.  ],
        [ 2048.  ],
        [  114.  ],
        [ 4107.  ],
        [  266.  ],
        [87639.24]]], dtype=float32)>

In [27]:
yhat = model.predict(x_input)
print(yhat)


[[59.837173]]
